theme = "hyde"
baseURL = "/"
languageCode = "en-us"
title = "My New Web Site"

[Menus]
  main = [
      {Name = "About", URL = "content/About"},
      {Name = "Projects", URL = "/content"},
      {Name = "Github", URL = "https://github.com/c-myang/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/username/"}
  ]
  
[params]
  description = "Hello! Welcome to my STA304 Site"

